"""empty message

Revision ID: 10b0d388a5f0
Revises: beb2e946ae1d
Create Date: 2025-03-25 20:22:58.465892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10b0d388a5f0'
down_revision: Union[str, None] = 'beb2e946ae1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('therapy', postgresql.ENUM('CBT', 'PSY_ANALISYS', 'COUCHING', 'GESTALT', 'IDK', name='therapyenum'), nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'therapy')
    # ### end Alembic commands ###
