"""empty message

Revision ID: 23383944afd6
Revises: 10b0d388a5f0
Create Date: 2025-03-25 22:31:46.270068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23383944afd6'
down_revision: Union[str, None] = '10b0d388a5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscribe_expired', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscribe_expired')
    # ### end Alembic commands ###
