"""empty message

Revision ID: ebf88e3a9b91
Revises: 23383944afd6
Create Date: 2025-03-26 01:35:48.851854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf88e3a9b91'
down_revision: Union[str, None] = '23383944afd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit_variants', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposit_variants', 'name')
    # ### end Alembic commands ###
