services:
  psy_bot:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: psy_bot
    restart: on-failure
    env_file: .env
    depends_on:
      - psy_db
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ../src/db/migrations:/opt/app/db/migrations
    ports:
      - 9002:5000
    networks:
      - psy_network

  psy_db:
    container_name: psy_db
    image: postgres
    env_file: .env
    environment:
      - TZ=Europe/Moscow
    volumes:
      - psy_db_data:/var/lib/postgresql/data

volumes:
  psy_db_data:
    driver: local

networks:
  psy_network:
    driver: bridge
